### ISSUE TITLE
Homework Week 10

### ISSUE THREAD

**Issue by ptums** [gregswanson/liri-node-app#1]
Hey Greg, I went through your liri program. You got spotify working in newTry.js, but it doesn't look like the other things work. Do you want to schedule some one-on-one time to go over it and get it working?

Peter

**Comment by gregswanson** [comment]
Sure. If it's not working then the wrong file was uploaded. All parts were definitely working. I'll look into it.

**Comment by gregswanson** [comment]
Everything should be working in the liri.js file. Each of the results was logged in the log.txt file.
